@api_url = http://localhost:3000/api
@token = 
@userId = 1
@slotId = 3
@storeId = 1
@collectionId = 1

### Create Assignment
POST {{api_url}}/assignments
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "userId": {{userId}},
  "slotId": {{slotId}},
  "storeId": {{storeId}},
  "collectionId": {{collectionId}}
}

### Get Assignments by Collection ID
GET {{api_url}}/collections/{{collectionId}}/assignments
Authorization: Bearer {{token}}

### Update Assignment
PUT {{api_url}}/assignments/{{collectionId}}/{{userId}}/{{slotId}}/{{storeId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "newUserId": 2,
  "newSlotId": 2,
  "newStoreId": 2,
  "newCollectionId": 1
}

### Delete Assignment
DELETE {{api_url}}/assignments/{{collectionId}}/{{userId}}/{{slotId}}/{{storeId}}
Authorization: Bearer {{token}}
