@api_url = https://api.restos-coeur.cleanascode.fr/api
@token = 
@api_key = your-api-key-change-in-production

### Create Store
POST {{api_url}}/stores
Content-Type: application/json
Authorization: Bearer {{token}}
X-API-Key: {{api_key}}

{
  "title": "Magasin Paris 15",
  "zoneId": 1,
  "openingTime": "08:30",
  "closingTime": "19:00",
  "isOpenSunday": false,
  "minVolunteers": 2,
  "idealVolunteers": 5
}

### Get All Stores
GET {{api_url}}/stores
Authorization: Bearer {{token}}
X-API-Key: {{api_key}}

### Get Store by ID
GET {{api_url}}/stores/1
Authorization: Bearer {{token}}
X-API-Key: {{api_key}}

### Update Store
PUT {{api_url}}/stores/1
Content-Type: application/json
Authorization: Bearer {{token}}
X-API-Key: {{api_key}}

{
  "title": "Magasin Paris 15 - Updated",
  "zoneId": 1,
  "openingTime": "09:00",
  "closingTime": "18:30",
  "isOpenSunday": true,
  "minVolunteers": 3,
  "idealVolunteers": 7
}

### Delete Store
DELETE {{api_url}}/stores/1
Authorization: Bearer {{token}}
X-API-Key: {{api_key}}
