@api_url = https://api.restos-coeur.cleanascode.fr/api

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjExLCJpYXQiOjE3Nzg2NjYzNDQsImV4cCI6MTc3ODc1Mjc0NH0.xnkwg_0weTQaw9VRSzAw7Y-uh8PHGT1nr61akfwdzvA
@api_key = your-api-key-change-in-production

### Create User
POST {{api_url}}/users
Content-Type: application/json
Authorization: Bearer {{token}}
X-API-Key: {{api_key}}

{
  "lastName": "SEGUIN",
  "firstName": "Augustin",
  "birthdate": "1998-06-15",
  "codePostal": "75011",
  "email": "augustin.seguin@inetum.com",
  "phoneNumber": "0685346728",
  "isActive": true,
  "isAdmin": true,
  "type": "permanent",
  "password": "password123"
}

### Create Admin User
POST {{api_url}}/users
Content-Type: application/json
Authorization: Bearer {{token}}
X-API-Key: {{api_key}}

{
  "lastName": "Admin",
  "firstName": "Super",
  "birthdate": "1985-09-30",
  "codePostal": "69003",
  "email": "admin@example.com",
  "phoneNumber": "0698765432",
  "password": "password123",
  "isActive": true,
  "isAdmin": true,
  "type": "permanent"
}

### Get All Users
GET {{api_url}}/users
Authorization: Bearer {{token}}
X-API-Key: {{api_key}}

### Get User by ID
GET {{api_url}}/users/1
Authorization: Bearer {{token}}
X-API-Key: {{api_key}}

### Get Active Admins
GET {{api_url}}/users/admins
Authorization: Bearer {{token}}
X-API-Key: {{api_key}}

### Update User
PUT {{api_url}}/users/1
Content-Type: application/json
Authorization: Bearer {{token}}
X-API-Key: {{api_key}}

{
  "lastName": "Dupont",
  "firstName": "Jean-Pierre",
  "birthdate": "1990-05-14",
  "codePostal": "75012",
  "email": "admin@example.com",
  "phoneNumber": "0612345678",
  "isActive": true,
  "isAdmin": true,
  "type": "occasional",
  "password": "password123",
}

### Delete User
DELETE {{api_url}}/users/1
Authorization: Bearer {{token}}
X-API-Key: {{api_key}}
